name: habito
description: Build habits in 21 days
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  flutter_iconpicker: ^1.1.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  email_validator: ^1.0.0
  scoped_model: ^1.0.1
  share: ^0.6.4+2
  easy_dialog: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: productsans
      fonts:
        - asset: assets/productsans.ttf
        - asset: assets/productsans_bold.ttf
          weight: 800
